/*
 * ForKMDHTTPAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using ForKMDHTTPAPI.Standard.Controllers;
using ForKMDHTTPAPI.Standard.Http.Client;
using ForKMDHTTPAPI.Standard.Utilities;

namespace ForKMDHTTPAPI.Standard
{
    public partial class ForKMDHTTPAPIClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public ForKMDHTTPAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public ForKMDHTTPAPIClient(string xKMDAPIToken)
        {
            Configuration.XKMDAPIToken = xKMDAPIToken;
        }
        #endregion
    }
}