/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using AlgodRESTAPI.Standard.Controllers;
using AlgodRESTAPI.Standard.Http.Client;
using AlgodRESTAPI.Standard.Utilities;

namespace AlgodRESTAPI.Standard
{
    public partial class AlgodRESTAPIClient
    {

        /// <summary>
        /// Singleton access to Client controller
        /// </summary>
        public APIController Client
        {
            get
            {
                return APIController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public AlgodRESTAPIClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public AlgodRESTAPIClient(string xAlgoAPIToken)
        {
            Configuration.XAlgoAPIToken = xAlgoAPIToken;
        }
        #endregion
    }
}