/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class AssetList : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.Asset> assets;

        /// <summary>
        /// AssetList is a list of assets
        /// </summary>
        [JsonProperty("assets")]
        public List<Models.Asset> Assets 
        { 
            get 
            {
                return this.assets; 
            } 
            set 
            {
                this.assets = value;
                onPropertyChanged("Assets");
            }
        }
    }
} 