/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class AssetFreezeTransactionType : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string acct;
        private bool freeze;
        private int id;

        /// <summary>
        /// Account specifies the account where the asset is being frozen or thawed.
        /// </summary>
        [JsonProperty("acct")]
        public string Acct 
        { 
            get 
            {
                return this.acct; 
            } 
            set 
            {
                this.acct = value;
                onPropertyChanged("Acct");
            }
        }

        /// <summary>
        /// NewFreezeStatus specifies the new freeze status.
        /// </summary>
        [JsonProperty("freeze")]
        public bool Freeze 
        { 
            get 
            {
                return this.freeze; 
            } 
            set 
            {
                this.freeze = value;
                onPropertyChanged("Freeze");
            }
        }

        /// <summary>
        /// AssetID is the asset being configured (or empty if creating)
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }
    }
} 