/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class AssetTransferTransactionType : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int amt;
        private string closeto;
        private int id;
        private string rcv;
        private string snd;

        /// <summary>
        /// Amount is the amount being transferred.
        /// </summary>
        [JsonProperty("amt")]
        public int Amt 
        { 
            get 
            {
                return this.amt; 
            } 
            set 
            {
                this.amt = value;
                onPropertyChanged("Amt");
            }
        }

        /// <summary>
        /// CloseTo is the destination for remaining funds (if closing).
        /// </summary>
        [JsonProperty("closeto")]
        public string Closeto 
        { 
            get 
            {
                return this.closeto; 
            } 
            set 
            {
                this.closeto = value;
                onPropertyChanged("Closeto");
            }
        }

        /// <summary>
        /// AssetID is the asset being configured (or empty if creating)
        /// </summary>
        [JsonProperty("id")]
        public int Id 
        { 
            get 
            {
                return this.id; 
            } 
            set 
            {
                this.id = value;
                onPropertyChanged("Id");
            }
        }

        /// <summary>
        /// Receiver is the recipient account.
        /// </summary>
        [JsonProperty("rcv")]
        public string Rcv 
        { 
            get 
            {
                return this.rcv; 
            } 
            set 
            {
                this.rcv = value;
                onPropertyChanged("Rcv");
            }
        }

        /// <summary>
        /// Sender is the source account (if using clawback).
        /// </summary>
        [JsonProperty("snd")]
        public string Snd 
        { 
            get 
            {
                return this.snd; 
            } 
            set 
            {
                this.snd = value;
                onPropertyChanged("Snd");
            }
        }
    }
} 