/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class BuildVersionContainsTheCurrentAlgodBuildVersionInformation : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string branch;
        private long buildNumber;
        private string channel;
        private string commitHash;
        private long major;
        private long minor;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("branch")]
        public string Branch 
        { 
            get 
            {
                return this.branch; 
            } 
            set 
            {
                this.branch = value;
                onPropertyChanged("Branch");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("build_number")]
        public long BuildNumber 
        { 
            get 
            {
                return this.buildNumber; 
            } 
            set 
            {
                this.buildNumber = value;
                onPropertyChanged("BuildNumber");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("channel")]
        public string Channel 
        { 
            get 
            {
                return this.channel; 
            } 
            set 
            {
                this.channel = value;
                onPropertyChanged("Channel");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("commit_hash")]
        public string CommitHash 
        { 
            get 
            {
                return this.commitHash; 
            } 
            set 
            {
                this.commitHash = value;
                onPropertyChanged("CommitHash");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("major")]
        public long Major 
        { 
            get 
            {
                return this.major; 
            } 
            set 
            {
                this.major = value;
                onPropertyChanged("Major");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("minor")]
        public long Minor 
        { 
            get 
            {
                return this.minor; 
            } 
            set 
            {
                this.minor = value;
                onPropertyChanged("Minor");
            }
        }
    }
} 