/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class KeyregTransactionType : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string selkey;
        private int? votefst;
        private int? votekd;
        private string votekey;
        private int? votelst;

        /// <summary>
        /// SelectionPK is the VRF public key used in key registration transactions
        /// </summary>
        [JsonProperty("selkey")]
        public string Selkey 
        { 
            get 
            {
                return this.selkey; 
            } 
            set 
            {
                this.selkey = value;
                onPropertyChanged("Selkey");
            }
        }

        /// <summary>
        /// VoteFirst is the first round this participation key is valid
        /// </summary>
        [JsonProperty("votefst")]
        public int? Votefst 
        { 
            get 
            {
                return this.votefst; 
            } 
            set 
            {
                this.votefst = value;
                onPropertyChanged("Votefst");
            }
        }

        /// <summary>
        /// VoteKeyDilution is the dilution for the 2-level participation key
        /// </summary>
        [JsonProperty("votekd")]
        public int? Votekd 
        { 
            get 
            {
                return this.votekd; 
            } 
            set 
            {
                this.votekd = value;
                onPropertyChanged("Votekd");
            }
        }

        /// <summary>
        /// VotePK is the participation public key used in key registration transactions
        /// </summary>
        [JsonProperty("votekey")]
        public string Votekey 
        { 
            get 
            {
                return this.votekey; 
            } 
            set 
            {
                this.votekey = value;
                onPropertyChanged("Votekey");
            }
        }

        /// <summary>
        /// VoteLast is the last round this participation key is valid
        /// </summary>
        [JsonProperty("votelst")]
        public int? Votelst 
        { 
            get 
            {
                return this.votelst; 
            } 
            set 
            {
                this.votelst = value;
                onPropertyChanged("Votelst");
            }
        }
    }
} 