/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class NodeStatus : BaseModel 
    {
        // These fields hold the values for the public properties.
        private long catchupTime;
        private bool hasSyncedSinceStartup;
        private string lastConsensusVersion;
        private int lastRound;
        private string nextConsensusVersion;
        private int nextConsensusVersionRound;
        private bool nextConsensusVersionSupported;
        private long timeSinceLastRound;

        /// <summary>
        /// CatchupTime in nanoseconds
        /// </summary>
        [JsonProperty("catchupTime")]
        public long CatchupTime 
        { 
            get 
            {
                return this.catchupTime; 
            } 
            set 
            {
                this.catchupTime = value;
                onPropertyChanged("CatchupTime");
            }
        }

        /// <summary>
        /// HasSyncedSinceStartup indicates whether a round has completed since startup
        /// </summary>
        [JsonProperty("hasSyncedSinceStartup")]
        public bool HasSyncedSinceStartup 
        { 
            get 
            {
                return this.hasSyncedSinceStartup; 
            } 
            set 
            {
                this.hasSyncedSinceStartup = value;
                onPropertyChanged("HasSyncedSinceStartup");
            }
        }

        /// <summary>
        /// LastVersion indicates the last consensus version supported
        /// </summary>
        [JsonProperty("lastConsensusVersion")]
        public string LastConsensusVersion 
        { 
            get 
            {
                return this.lastConsensusVersion; 
            } 
            set 
            {
                this.lastConsensusVersion = value;
                onPropertyChanged("LastConsensusVersion");
            }
        }

        /// <summary>
        /// LastRound indicates the last round seen
        /// </summary>
        [JsonProperty("lastRound")]
        public int LastRound 
        { 
            get 
            {
                return this.lastRound; 
            } 
            set 
            {
                this.lastRound = value;
                onPropertyChanged("LastRound");
            }
        }

        /// <summary>
        /// NextVersion of consensus protocol to use
        /// </summary>
        [JsonProperty("nextConsensusVersion")]
        public string NextConsensusVersion 
        { 
            get 
            {
                return this.nextConsensusVersion; 
            } 
            set 
            {
                this.nextConsensusVersion = value;
                onPropertyChanged("NextConsensusVersion");
            }
        }

        /// <summary>
        /// NextVersionRound is the round at which the next consensus version will apply
        /// </summary>
        [JsonProperty("nextConsensusVersionRound")]
        public int NextConsensusVersionRound 
        { 
            get 
            {
                return this.nextConsensusVersionRound; 
            } 
            set 
            {
                this.nextConsensusVersionRound = value;
                onPropertyChanged("NextConsensusVersionRound");
            }
        }

        /// <summary>
        /// NextVersionSupported indicates whether the next consensus version is supported by this node
        /// </summary>
        [JsonProperty("nextConsensusVersionSupported")]
        public bool NextConsensusVersionSupported 
        { 
            get 
            {
                return this.nextConsensusVersionSupported; 
            } 
            set 
            {
                this.nextConsensusVersionSupported = value;
                onPropertyChanged("NextConsensusVersionSupported");
            }
        }

        /// <summary>
        /// TimeSinceLastRound in nanoseconds
        /// </summary>
        [JsonProperty("timeSinceLastRound")]
        public long TimeSinceLastRound 
        { 
            get 
            {
                return this.timeSinceLastRound; 
            } 
            set 
            {
                this.timeSinceLastRound = value;
                onPropertyChanged("TimeSinceLastRound");
            }
        }
    }
} 