/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class Participation : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string partpkb64;
        private int votefst;
        private int votekd;
        private int votelst;
        private string vrfpkb64;

        /// <summary>
        /// ParticipationPK is the root participation public key (if any) currently registered for this round
        /// </summary>
        [JsonProperty("partpkb64")]
        public string Partpkb64 
        { 
            get 
            {
                return this.partpkb64; 
            } 
            set 
            {
                this.partpkb64 = value;
                onPropertyChanged("Partpkb64");
            }
        }

        /// <summary>
        /// VoteFirst is the first round for which this participation is valid.
        /// </summary>
        [JsonProperty("votefst")]
        public int Votefst 
        { 
            get 
            {
                return this.votefst; 
            } 
            set 
            {
                this.votefst = value;
                onPropertyChanged("Votefst");
            }
        }

        /// <summary>
        /// VoteKeyDilution is the number of subkeys in for each batch of participation keys.
        /// </summary>
        [JsonProperty("votekd")]
        public int Votekd 
        { 
            get 
            {
                return this.votekd; 
            } 
            set 
            {
                this.votekd = value;
                onPropertyChanged("Votekd");
            }
        }

        /// <summary>
        /// VoteLast is the last round for which this participation is valid.
        /// </summary>
        [JsonProperty("votelst")]
        public int Votelst 
        { 
            get 
            {
                return this.votelst; 
            } 
            set 
            {
                this.votelst = value;
                onPropertyChanged("Votelst");
            }
        }

        /// <summary>
        /// VRFPK is the selection public key (if any) currently registered for this round
        /// </summary>
        [JsonProperty("vrfpkb64")]
        public string Vrfpkb64 
        { 
            get 
            {
                return this.vrfpkb64; 
            } 
            set 
            {
                this.vrfpkb64 = value;
                onPropertyChanged("Vrfpkb64");
            }
        }
    }
} 