/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class PaymentTransactionType : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int amount;
        private string close;
        private int? closeamount;
        private int? closerewards;
        private string to;
        private int? torewards;

        /// <summary>
        /// Amount is the amount of MicroAlgos intended to be transferred
        /// </summary>
        [JsonProperty("amount")]
        public int Amount 
        { 
            get 
            {
                return this.amount; 
            } 
            set 
            {
                this.amount = value;
                onPropertyChanged("Amount");
            }
        }

        /// <summary>
        /// CloseRemainderTo is the address the sender closed to
        /// </summary>
        [JsonProperty("close")]
        public string Close 
        { 
            get 
            {
                return this.close; 
            } 
            set 
            {
                this.close = value;
                onPropertyChanged("Close");
            }
        }

        /// <summary>
        /// CloseAmount is the amount sent to CloseRemainderTo, for committed transaction
        /// </summary>
        [JsonProperty("closeamount")]
        public int? Closeamount 
        { 
            get 
            {
                return this.closeamount; 
            } 
            set 
            {
                this.closeamount = value;
                onPropertyChanged("Closeamount");
            }
        }

        /// <summary>
        /// CloseRewards is the amount of pending rewards applied to the CloseRemainderTo
        /// account as part of this transaction.
        /// </summary>
        [JsonProperty("closerewards")]
        public int? Closerewards 
        { 
            get 
            {
                return this.closerewards; 
            } 
            set 
            {
                this.closerewards = value;
                onPropertyChanged("Closerewards");
            }
        }

        /// <summary>
        /// To is the receiver's address
        /// </summary>
        [JsonProperty("to")]
        public string To 
        { 
            get 
            {
                return this.to; 
            } 
            set 
            {
                this.to = value;
                onPropertyChanged("To");
            }
        }

        /// <summary>
        /// ToRewards is the amount of pending rewards applied to the To account
        /// as part of this transaction.
        /// </summary>
        [JsonProperty("torewards")]
        public int? Torewards 
        { 
            get 
            {
                return this.torewards; 
            } 
            set 
            {
                this.torewards = value;
                onPropertyChanged("Torewards");
            }
        }
    }
} 