/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class PendingTransactions : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int totalTxns;
        private Models.TransactionList truncatedTxns;

        /// <summary>
        /// TotalTxns
        /// </summary>
        [JsonProperty("totalTxns")]
        public int TotalTxns 
        { 
            get 
            {
                return this.totalTxns; 
            } 
            set 
            {
                this.totalTxns = value;
                onPropertyChanged("TotalTxns");
            }
        }

        /// <summary>
        /// TransactionList contains a list of transactions
        /// </summary>
        [JsonProperty("truncatedTxns")]
        public Models.TransactionList TruncatedTxns 
        { 
            get 
            {
                return this.truncatedTxns; 
            } 
            set 
            {
                this.truncatedTxns = value;
                onPropertyChanged("TruncatedTxns");
            }
        }
    }
} 