/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class TransactionID : BaseModel 
    {
        // These fields hold the values for the public properties.
        private string txId;

        /// <summary>
        /// TxId is the string encoding of the transaction hash
        /// </summary>
        [JsonProperty("txId")]
        public string TxId 
        { 
            get 
            {
                return this.txId; 
            } 
            set 
            {
                this.txId = value;
                onPropertyChanged("TxId");
            }
        }
    }
} 