/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class TransactionResults : BaseModel 
    {
        // These fields hold the values for the public properties.
        private int? createdasset;

        /// <summary>
        /// CreatedAssetIndex indicates the asset index of an asset created by this txn
        /// </summary>
        [JsonProperty("createdasset")]
        public int? Createdasset 
        { 
            get 
            {
                return this.createdasset; 
            } 
            set 
            {
                this.createdasset = value;
                onPropertyChanged("Createdasset");
            }
        }
    }
} 