/*
 * AlgodRESTAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using AlgodRESTAPI.Standard;
using AlgodRESTAPI.Standard.Utilities;


namespace AlgodRESTAPI.Standard.Models
{
    public class VersionContainsTheCurrentAlgodVersion : BaseModel 
    {
        // These fields hold the values for the public properties.
        private Models.BuildVersionContainsTheCurrentAlgodBuildVersionInformation build;
        private string genesisHashB64;
        private string genesisId;
        private List<string> versions;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("build")]
        public Models.BuildVersionContainsTheCurrentAlgodBuildVersionInformation Build 
        { 
            get 
            {
                return this.build; 
            } 
            set 
            {
                this.build = value;
                onPropertyChanged("Build");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("genesis_hash_b64")]
        public string GenesisHashB64 
        { 
            get 
            {
                return this.genesisHashB64; 
            } 
            set 
            {
                this.genesisHashB64 = value;
                onPropertyChanged("GenesisHashB64");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("genesis_id")]
        public string GenesisId 
        { 
            get 
            {
                return this.genesisId; 
            } 
            set 
            {
                this.genesisId = value;
                onPropertyChanged("GenesisId");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("versions")]
        public List<string> Versions 
        { 
            get 
            {
                return this.versions; 
            } 
            set 
            {
                this.versions = value;
                onPropertyChanged("Versions");
            }
        }
    }
} 