/*
 * ForKMDHTTPAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ForKMDHTTPAPI.Standard;
using ForKMDHTTPAPI.Standard.Utilities;


namespace ForKMDHTTPAPI.Standard.Models
{
    public class APIV1POSTMultisigExportResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool? error;
        private string message;
        private int? multisigVersion;
        private List<int> pks;
        private int? threshold;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("error")]
        public bool? Error 
        { 
            get 
            {
                return this.error; 
            } 
            set 
            {
                this.error = value;
                onPropertyChanged("Error");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("message")]
        public string Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("multisig_version")]
        public int? MultisigVersion 
        { 
            get 
            {
                return this.multisigVersion; 
            } 
            set 
            {
                this.multisigVersion = value;
                onPropertyChanged("MultisigVersion");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("pks")]
        public List<int> Pks 
        { 
            get 
            {
                return this.pks; 
            } 
            set 
            {
                this.pks = value;
                onPropertyChanged("Pks");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("threshold")]
        public int? Threshold 
        { 
            get 
            {
                return this.threshold; 
            } 
            set 
            {
                this.threshold = value;
                onPropertyChanged("Threshold");
            }
        }
    }
} 