/*
 * ForKMDHTTPAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ForKMDHTTPAPI.Standard;
using ForKMDHTTPAPI.Standard.Utilities;


namespace ForKMDHTTPAPI.Standard.Models
{
    public class APIV1POSTWalletResponse : BaseModel 
    {
        // These fields hold the values for the public properties.
        private bool? error;
        private string message;
        private Models.APIV1Wallet wallet;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("error")]
        public bool? Error 
        { 
            get 
            {
                return this.error; 
            } 
            set 
            {
                this.error = value;
                onPropertyChanged("Error");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("message")]
        public string Message 
        { 
            get 
            {
                return this.message; 
            } 
            set 
            {
                this.message = value;
                onPropertyChanged("Message");
            }
        }

        /// <summary>
        /// APIV1Wallet is the API's representation of a wallet
        /// </summary>
        [JsonProperty("wallet")]
        public Models.APIV1Wallet Wallet 
        { 
            get 
            {
                return this.wallet; 
            } 
            set 
            {
                this.wallet = value;
                onPropertyChanged("Wallet");
            }
        }
    }
} 