/*
 * ForKMDHTTPAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ForKMDHTTPAPI.Standard;
using ForKMDHTTPAPI.Standard.Utilities;


namespace ForKMDHTTPAPI.Standard.Models
{
    public class CreateWalletRequest : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<int> masterDerivationKey;
        private string walletDriverName;
        private string walletName;
        private string walletPassword;

        /// <summary>
        /// MasterDerivationKey is used to derive ed25519 keys for use in wallets
        /// </summary>
        [JsonProperty("master_derivation_key")]
        public List<int> MasterDerivationKey 
        { 
            get 
            {
                return this.masterDerivationKey; 
            } 
            set 
            {
                this.masterDerivationKey = value;
                onPropertyChanged("MasterDerivationKey");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("wallet_driver_name")]
        public string WalletDriverName 
        { 
            get 
            {
                return this.walletDriverName; 
            } 
            set 
            {
                this.walletDriverName = value;
                onPropertyChanged("WalletDriverName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("wallet_name")]
        public string WalletName 
        { 
            get 
            {
                return this.walletName; 
            } 
            set 
            {
                this.walletName = value;
                onPropertyChanged("WalletName");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("wallet_password")]
        public string WalletPassword 
        { 
            get 
            {
                return this.walletPassword; 
            } 
            set 
            {
                this.walletPassword = value;
                onPropertyChanged("WalletPassword");
            }
        }
    }
} 