/*
 * ForKMDHTTPAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ForKMDHTTPAPI.Standard;
using ForKMDHTTPAPI.Standard.Utilities;


namespace ForKMDHTTPAPI.Standard.Models
{
    public class MultisigSig : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<Models.MultisigSubsig> subsigs;
        private int? threshold;
        private int? version;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Subsigs")]
        public List<Models.MultisigSubsig> Subsigs 
        { 
            get 
            {
                return this.subsigs; 
            } 
            set 
            {
                this.subsigs = value;
                onPropertyChanged("Subsigs");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Threshold")]
        public int? Threshold 
        { 
            get 
            {
                return this.threshold; 
            } 
            set 
            {
                this.threshold = value;
                onPropertyChanged("Threshold");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Version")]
        public int? Version 
        { 
            get 
            {
                return this.version; 
            } 
            set 
            {
                this.version = value;
                onPropertyChanged("Version");
            }
        }
    }
} 