/*
 * ForKMDHTTPAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ForKMDHTTPAPI.Standard;
using ForKMDHTTPAPI.Standard.Utilities;


namespace ForKMDHTTPAPI.Standard.Models
{
    public class APIV1WalletHandle : BaseModel 
    {
        // These fields hold the values for the public properties.
        private long? expiresSeconds;
        private Models.APIV1Wallet wallet;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("expires_seconds")]
        public long? ExpiresSeconds 
        { 
            get 
            {
                return this.expiresSeconds; 
            } 
            set 
            {
                this.expiresSeconds = value;
                onPropertyChanged("ExpiresSeconds");
            }
        }

        /// <summary>
        /// APIV1Wallet is the API's representation of a wallet
        /// </summary>
        [JsonProperty("wallet")]
        public Models.APIV1Wallet Wallet 
        { 
            get 
            {
                return this.wallet; 
            } 
            set 
            {
                this.wallet = value;
                onPropertyChanged("Wallet");
            }
        }
    }
} 