/*
 * ForKMDHTTPAPI.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using ForKMDHTTPAPI.Standard;
using ForKMDHTTPAPI.Standard.Utilities;


namespace ForKMDHTTPAPI.Standard.Models
{
    public class MultisigSubsig : BaseModel 
    {
        // These fields hold the values for the public properties.
        private List<int> key;
        private List<int> sig;

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Key")]
        public List<int> Key 
        { 
            get 
            {
                return this.key; 
            } 
            set 
            {
                this.key = value;
                onPropertyChanged("Key");
            }
        }

        /// <summary>
        /// TODO: Write general description for this method
        /// </summary>
        [JsonProperty("Sig")]
        public List<int> Sig 
        { 
            get 
            {
                return this.sig; 
            } 
            set 
            {
                this.sig = value;
                onPropertyChanged("Sig");
            }
        }
    }
} 